### ISSUE TITLE
第一期反馈

### ISSUE THREAD

**Issue by rupertqin** [uicestone/SkillBank-mobile-front#1]
## 第一波页面反馈1.txt
- 1,2,3 黄色课程类别栏目  这里的几个问题，用的是系统的滚动条才出现的，估计要重写
- 6  上下两部分都是自适应的，我没有限制高度，下部因为字体 size 的原因显得长了，现已调整
## 第一波页面反馈2.docx
- 1.1 这应该是旋转屏后出现的， 用的是插件， 要重写
## 第一波页面反馈4.docx
- 好像只有在微信里才出现往下跑的情况， 好像 iOS 没有这个问题

**Comment by rupertqin** [comment]
输入框在微信里闪动的问题，我再研究下，可能是布局的问题，其他页面的 input 没有闪动

**Comment by uicestone** [comment]
嗯，微信里界面往下跑的问题麻烦也看一下，这个网页绝大部分情况是在微信中被访问

**Comment by Elainezhou11** [comment]
网页整个往下跑还常出现在按了浏览器返回按钮后之前的那个页面上。图我贴微信群里

**Comment by Elainezhou11** [comment]
关注点后的效果是底色变灰＃A6AFB2，整个底色区域可点。两态，再点就恢复原来颜色
![image](https://cloud.githubusercontent.com/assets/10989048/6210028/6021f022-b606-11e4-885d-9df3fb12bd79.png)

**Comment by Elainezhou11** [comment]
还有两个问题：
1. 在personal的页面上http://www.skillbank.cn/m/personal/6，如果最下面tab上的评价为0，这个tab设为不可点,做一个不可点的样式
2. 还有一个问题想讨论一下可行性，就是如果我在课程列表向下滚了一会儿，找到一堂课后点击进入课程介绍页，当我按浏览器返回时，我们返回到课程列表我刚刚选中的那堂课的位置吗？

**Comment by rupertqin** [comment]
1.  ok
2.  这样要用到前端路由，最好课程列表页中 初始列表“全部”也作为 Ajax, 要不然每次进入这个页面可能多加载一次 “全部”。 也可以不要使用 Ajax, 也能达到这个效果，还方便点
